name: Bug Report
description: 报告一个bug来帮助我们改进项目
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:

  - type: markdown
    attributes:
      value: |
        感谢您报告bug！请填写以下信息来帮助我们快速定位和解决问题。

  - type: input
    id: python-version
    attributes:
      label: Python版本
      description: 您使用的Python版本是什么？
      placeholder: "例如: 3.9.7"
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: 操作系统
      description: 您使用的操作系统是什么？
      placeholder: "例如: Windows 10, macOS Big Sur, Ubuntu 20.04"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么？
      description: 请描述您遇到的问题。
      placeholder: "请详细描述您遇到的问题..."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 期望的行为是什么？
      description: 您期望程序如何工作？
      placeholder: "请描述您期望的正确行为..."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 重现步骤
      description: 请提供重现问题的具体步骤。
      placeholder: |
        1. 运行 '...'
        2. 更改参数为 '...'
        3. 查看输出 '...'
        4. 看到错误
    validations:
      required: true

  - type: textarea
    id: error-message
    attributes:
      label: 错误信息
      description: 请提供完整的错误信息（如果有的话）。
      placeholder: "请粘贴完整的错误消息..."
    validations:
      required: false

  - type: textarea
    id: code-snippet
    attributes:
      label: 相关代码
      description: 如果适用，请提供相关的代码片段。
      placeholder: "```python\n# 您的代码\n```"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 您认为这个问题的优先级如何？
      options:
        - "Low"
        - "Medium"
        - "High"
        - "Critical"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 请确认您已经检查了以下项目：
      options:
        - label: 我已经搜索了现有的Issues，确保这个问题没有重复
          required: true
        - label: 我使用的是最新版本的代码
          required: true
        - label: 我提供了所有必要的信息来重现问题
          required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 额外信息
      description: 还有其他任何可以帮助我们理解问题的信息吗？
      placeholder: "任何其他背景信息、截图等..."
    validations:
      required: false